# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField()),
                ('station_name', models.CharField(max_length=64)),
                ('transmitter', models.CharField(max_length=64)),
                ('power', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.TextField()),
            ],
        ),
    ]
